[package]
name = "lockless-datastructures"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = "0.12.5"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
